//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_GVFT.Business.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credits()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        public string Code_credits { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> Expire_date { get; set; }
        public int Type_credit { get; set; }
        public Nullable<int> Cant { get; set; }
        public int Expiry_mode { get; set; }
        public Nullable<int> Qty_sold { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
        public virtual Type_Credits Type_Credits { get; set; }
    }
}
