//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_GVFT.Business.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_FT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Login_FT()
        {
            this.Invoice = new HashSet<Invoice>();
            this.Log = new HashSet<Log>();
            this.purchase_of_merchandise = new HashSet<purchase_of_merchandise>();
        }
    
        public int Id { get; set; }
        public string Login_name { get; set; }
        public string Login_pass { get; set; }
        public int Roles { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> Registration_date { get; set; }
        public int Id_employee { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> Last_login { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_of_merchandise> purchase_of_merchandise { get; set; }
        public virtual Roles_Account Roles_Account { get; set; }
        public virtual Status_Account Status_Account { get; set; }
    }
}
