//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_GVFT.Business.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_of_merchandise
    {
        public int Id { get; set; }
        public string Detail { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date_purchase { get; set; }
        public int Quantity { get; set; }
        public int Id_merchandise { get; set; }
        public Nullable<int> Id_supplier { get; set; }
        public int Id_user { get; set; }
    
        public virtual Login_FT Login_FT { get; set; }
        public virtual Merchandise Merchandise { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
